"""added Schedule Table

Revision ID: 01e83c32eb6e
Revises: ecb65ebd4ea1
Create Date: 2019-09-30 19:43:01.016506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e83c32eb6e'
down_revision = 'ecb65ebd4ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_date'), 'schedule', ['date'], unique=True)
    op.create_index(op.f('ix_schedule_user_id'), 'schedule', ['user_id'], unique=False)
    op.add_column('user', sa.Column('qualification', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_points'), 'user', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_points'), table_name='user')
    op.drop_column('user', 'qualification')
    op.drop_index(op.f('ix_schedule_user_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_date'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
